apiVersion: v1
kind: Service
metadata:
  name: py-app-service
  labels:
    app: py-app
spec:
  type: NodePort
  selector:
    app: py-app
  ports:
    - port:  5000
      targetPort: 8000
      nodePort: 30500
